import shlex
from pathlib import Path

from . import multinode

def create_vllm_batch_script(
        account: str,
        partition: str,
        nodes: str,
        gpus_per_node: str,
        time: str,
        memory: str,
        cpus_per_task: str,
        logs_dir: Path,
        input_file: Path,
        output_file: Path,
        job_name: str,
        slurm_config,
        mode: str = "batch",
        email: str = "",
):

    # Create SLURM job script
    job_script = [
        "#!/bin/bash",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --account={account}",
        f"#SBATCH --partition={partition}",
        f"#SBATCH --nodes={nodes}",
        f"#SBATCH --gpus-per-node={gpus_per_node}",
        f"#SBATCH --time={time}",
        f"#SBATCH --mem={memory}",
        f"#SBATCH --cpus-per-task={cpus_per_task}",
        f"#SBATCH --output={logs_dir}/%j.out",
        f"#SBATCH --error={logs_dir}/%j.err",
    ]

    # Add extra SBATCH directives if provided
    if slurm_config.extra_sbatch_args:
        for key, value in slurm_config.extra_sbatch_args.items():
            job_script.append(f"#SBATCH --{key}={value}")

    if mode == "serve":
        job_script.extend([
            f"#SBATCH --mail-type=FAIL",
            f"#SBATCH --mail-user={email}",
        ])

    job_script.extend([
        "# Create all necessary directories",
        "mkdir -p $DATA_INPUT_DIR $DATA_OUTPUT_DIR $MODELS_DIR $LOGS_DIR $CONTAINERS_DIR $APPTAINER_TMPDIR $APPTAINER_CACHEDIR $HF_HOME $VLLM_HOME $VLLM_MODELS $XDG_CACHE_HOME $FLASHINFER_WORKSPACE_BASE ",
        "",
        "# Start vLLM server",
        "",
        "echo hf_home: $HF_HOME",
        "echo vllm home: $VLLM_HOME",
        "echo vllm models: $VLLM_MODELS",
        "",
        "# Build container if needed (or if forced)",
        "if [ \"$LLMFLUX_FORCE_REBUILD\" = \"1\" ] || [ ! -f \"$CONTAINERS_DIR/llm_processor.sif\" ]; then",
        "    echo \"Building Container in ${CONTAINERS_DIR}\"",
        "    apptainer build --force $CONTAINERS_DIR/llm_processor.sif $CONTAINER_DEF",
        "    echo Container built successfully: ${?}",
        "fi",
        "",
        "# start serverwith clean environment",
        "# All APPTAINERENV_* variables are automatically passed in (prefix removed)",
        "# VLLM_MODEL_NAME contains the HuggingFace model name",
        "echo \"Using HuggingFace model: $VLLM_MODEL_NAME\"",
        "echo \"Port: $VLLM_PORT\"",
        "",
        "export APPTAINER_BIND_PATHS=\"$DATA_INPUT_DIR:/app/data/input,$DATA_OUTPUT_DIR:/app/data/output,$MODELS_DIR:/app/models,$LOGS_DIR:/app/logs,$VLLM_HOME:$VLLM_HOME,$HF_HOME:$HF_HOME,$XDG_CACHE_HOME:$XDG_CACHE_HOME,$FLASHINFER_WORKSPACE_BASE:$FLASHINFER_WORKSPACE_BASE\"",
        "if [ -d \"$VLLM_MODEL_NAME\" ]; then",
        "    echo \"Bind-mounting local model path: $VLLM_MODEL_NAME\"",
        "    export APPTAINER_BIND_PATHS=\"$APPTAINER_BIND_PATHS,$VLLM_MODEL_NAME:$VLLM_MODEL_NAME\"",
        "fi",
        "",
        "# Set HF_TOKEN for vLLM if available (for gated models)",
        "if [ -n \"$HF_TOKEN\" ]; then",
        "    echo \"HuggingFace token detected - will use for model authentication\"",
        "    export APPTAINERENV_HF_TOKEN=\"$HF_TOKEN\"",
        "fi",
        "",
        "# Pass SLURM-allocated GPU(s) into the container (--cleanenv strips CUDA_VISIBLE_DEVICES)",
        "export APPTAINERENV_CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}",
        *([
            "# Find a consecutive free port on this compute node",
            "find_free_port() {",
            "    local port=$1",
            "    while ss -tlnH 2>/dev/null | awk '{print $4}' | grep -q \":${port}$\"; do",
            "        port=$((port + 1))",
            "    done",
            "    echo $port",
            "}",
            "VLLM_PORT=$(find_free_port ${VLLM_PORT:-8000})",
            "export APPTAINERENV_VLLM_PORT=$VLLM_PORT",
            "echo \"Using port: $VLLM_PORT\"",
            "",
            "# Install cleanup trap early so the connection file (contains the API key)",
            "# and server are removed even if the job is cancelled with scancel (SIGTERM).",
            "CONNECTION_FILE=\"$HOME/.llmflux/serve/$SLURM_JOB_ID/connection.json\"",
            "trap 'rm -f \"$CONNECTION_FILE\"; pkill -f \"vllm serve\" || true' EXIT TERM INT",
            "",
        ] if mode == "serve" else []),
        # nodes > 1 replaces the single-node exec with an SPMD srun step; at
        # nodes == 1 the lines below are emitted unchanged, so single-node users
        # see a byte-identical script.
        *(multinode.preamble(nodes, gpus_per_node) if int(nodes) > 1 else []),
        *(multinode.launch() if int(nodes) > 1 else [
            "VERBOSE=1 apptainer exec --nv --cleanenv \\",
            "    --bind \"$APPTAINER_BIND_PATHS\" \\",
            "    ${CONTAINERS_DIR}/llm_processor.sif \\",
            "    python3 -m vllm.entrypoints.openai.api_server \\",
            "        --model \"$VLLM_MODEL_NAME\" \\",
            "        --host \"$VLLM_HOST\" \\",
            "        --port \"$VLLM_PORT\" \\",
        ] + ([
            "        --api-key \"$LLMFLUX_API_KEY\" \\",
        ] if mode == "serve" else []) + [
            "        $VLLM_ENGINE_ARGS &",
            "VLLM_PID=$!",
            "echo \"        PID: $VLLM_PID\"",
        ]),
        "echo \"\"",
        "# Wait for server",
        "echo \"[3/4] Waiting for server to be ready...\":",
        "SERVER_READY=false",
        "LLMFLUX_SERVER_TIMEOUT=${LLMFLUX_SERVER_TIMEOUT:-300}",
        "for i in $(seq 1 $LLMFLUX_SERVER_TIMEOUT); do",
        "    if curl -s \"http://localhost:$VLLM_PORT/health\" >/dev/null 2>&1; then",
        "        echo \"        ✓ Server ready!\"",
        "        SERVER_READY=true",
        "        break",
        "    fi",
        "    if ! ps -p $VLLM_PID > /dev/null; then",
        "        echo \"VLLM server died\"",
        "        exit 1",
        "    fi",
        "    [ $((i %15)) -eq 0 ] && echo \"        Still loading... ($i/${LLMFLUX_SERVER_TIMEOUT}s)\"",
        "    sleep 1",
        "done",
        "if [[ $SERVER_READY == \"false\" ]]; then",
        "    echo \"Server failed to load!\"",
        "    exit 1",
        "else",
        "    echo \"Server has started!\"",
        "fi",
        "# Check if model exists, try to pull if it doesn't",
        "echo \"\"",
        "# Test inference",
        "echo TEST",
        "echo Time to ask questions!",
        "",
        *([
            "# Write connection file for llmflux connect (restrict permissions — contains API key)",
            "# CONNECTION_FILE was defined earlier alongside the cleanup trap.",
            "(umask 077 && mkdir -p \"$(dirname $CONNECTION_FILE)\")",
            "chmod 700 \"$HOME/.llmflux\" \"$HOME/.llmflux/serve\" \"$(dirname $CONNECTION_FILE)\"",
            "(umask 077 && cat > \"$CONNECTION_FILE\" <<EOF",
            "{",
            "  \"job_id\": \"$SLURM_JOB_ID\",",
            "  \"node\": \"$(hostname)\",",
            "  \"port\": $VLLM_PORT,",
            "  \"model\": \"$VLLM_MODEL_NAME\",",
            "  \"api_key\": \"$LLMFLUX_API_KEY\",",
            "  \"engine\": \"vllm\",",
            "  \"started_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"",
            "}",
            "EOF",
            ")",
            "chmod 600 \"$CONNECTION_FILE\"",
            "echo \"Connection info written to $CONNECTION_FILE\"",
            "",
            "# Send ready notification email with connection details",
            f"LLMFLUX_EMAIL={shlex.quote(email)}",
            "mail -s \"LLMFlux serve job $SLURM_JOB_ID is ready\" -- \"$LLMFLUX_EMAIL\" <<MAIL_EOF",
            "Your LLMFlux serve job has finished loading and is ready to use.",
            "",
            "  Job ID:   $SLURM_JOB_ID",
            "  Endpoint: http://$(hostname):$VLLM_PORT/v1",
            "  API Key:  $LLMFLUX_API_KEY",
            "  Model:    $VLLM_MODEL_NAME",
            "  Engine:   vllm",
            "",
            "Example usage:",
            "",
            "  from openai import OpenAI",
            "  client = OpenAI(base_url=\"http://$(hostname):$VLLM_PORT/v1\", api_key=\"$LLMFLUX_API_KEY\")",
            "  response = client.chat.completions.create(",
            "      model=\"$VLLM_MODEL_NAME\",",
            "      messages=[{\"role\": \"user\", \"content\": \"Hello!\"}]",
            "  )",
            "",
            "To get connection details again:",
            "  llmflux connect $SLURM_JOB_ID",
            "MAIL_EOF",
            "",
            "# Keep alive until wall time or scancel",
            "wait $VLLM_PID",
        ] if mode == "serve" else [
            "# Run processor",
            "python3 -c \"",
            "import sys",
            "import os",
            "sys.path.append('$PROJECT_ROOT')",
            "from llmflux.core.config import Config",
            "from llmflux.processors import BatchProcessor",
            "",
            "# Ensure VLLM environment variables are available in Python",
            "vllm_port = os.environ.get('VLLM_PORT')",
            "if vllm_port:",
            "    os.environ['VLLM_HOST'] = f'http://localhost:{vllm_port}'",
            "",
            "# Load model configuration",
            "config = Config()",
            "model_identifier = os.environ.get('APPTAINERENV_MODEL_IDENTIFIER', 'Llama-3.2-3B-Instruct')",
            "engine = os.environ.get('APPTAINERENV_ENGINE', 'vllm')",
            "custom_config_path = os.environ.get('APPTAINERENV_CUSTOM_CONFIG_PATH') or None",
            "",
            "try:",
            "    model_config = config.load_model_config(model_identifier, custom_config_path=custom_config_path)",
            "    model_config.engine = engine",
            "except Exception as e:",
            "    print(f'Error loading model config for {model_identifier}: {e}')",
            "    model_config = config.load_model_config('Llama-3.2-3B-Instruct')",
            "    model_config.engine = engine",
            "",
            "print('Create batch processor with JSONL input')",
            "batch_processor = BatchProcessor(",
            "    model_config=model_config,",
            "    batch_size=int(os.environ.get('BATCH_SIZE', '4')),",
            "    save_frequency=int(os.environ.get('SAVE_FREQUENCY', '50')),",
            "    max_retries=int(os.environ.get('MAX_RETRIES', '3')),",
            "    retry_delay=float(os.environ.get('RETRY_DELAY', '1.0'))",
            ")",
            "print(f'batch processor: {batch_processor}')",
            "",
            "# Prepare run kwargs",
            "run_kwargs = {}",
            "",
            "# Add any other kwargs from environment variables",
            "for key in ['max_tokens', 'temperature', 'top_p', 'top_k']:",
            "    if key.upper() in os.environ:",
            "        run_kwargs[key] = os.environ[key.upper()]",
            "",
            f"batch_processor.run('{input_file}', '{output_file}', 'vllm', **run_kwargs)",
            "\"",
            "# Capture the processor's status before cleanup overwrites $?.",
            "LLMFLUX_PROC_RC=$?",
        ]),
        "",
        "# Cleanup",
        # In serve mode the EXIT/TERM/INT trap handles connection-file removal
        # and killing the server, so no explicit cleanup is needed here.
        *( ["pkill -f \"vllm serve\" || true"] if mode != "serve" else [] ),
        "# Only remove temporary directories that we created",
        "if [ -d \"$APPTAINER_TMPDIR\" ] && [ -w \"$APPTAINER_TMPDIR\" ]; then",
        "    rm -rf \"$APPTAINER_TMPDIR\"",
        "fi",
        "if [ -d \"$APPTAINER_CACHEDIR\" ] && [ -w \"$APPTAINER_CACHEDIR\" ]; then",
        "    rm -rf \"$APPTAINER_CACHEDIR\"",
        "fi",
        "echo \"Cleaning up...\"",
        "kill $VLLM_PID 2>/dev/null || true",
        "sleep 2",
        "kill -9 $VLLM_PID 2>/dev/null || true",
        "",
        *([
            "# Exit with the processor's status. Without this the script exits with\n"
            "# whatever cleanup returned, so a run whose every item failed still\n"
            "# reports success and the job looks complete.",
            "exit ${LLMFLUX_PROC_RC:-0}",
        ] if mode != "serve" else []),
    ])
    return job_script
